#+author: Julian Orchard <git@julianorchard.co.uk>
#+title: /emacs.org/
#+description: My literate emacs configuration, mainly for Windows 10 at the moment. 

This is my on-going project to  /b e c o m e/  an emacs user (from being a vimmer).

** Content                                                     :toc_3:quote:
#+BEGIN_QUOTE
  - [[#the-basics][The Basics]]
    - [[#about][About]]
    - [[#improve-start-up-time][Improve Start-Up Time]]
    - [[#maximise-window][Maximise Window]]
    - [[#scratch-buffer-and-startup-info][Scratch Buffer and Startup Info]]
    - [[#my-details][My Details]]
    - [[#escape-actually-escapes][Escape Actually Escapes]]
    - [[#mouse][Mouse]]
    - [[#parenthesis-mode][Parenthesis Mode]]
    - [[#minimizing-lockfiles-and-tempfiles][Minimizing Lockfiles and Tempfiles]]
    - [[#utf-8][UTF-8]]
    - [[#dialogue-boxes][Dialogue Boxes]]
    - [[#yesno-or-yn][Yes/No, or Y/N]]
    - [[#load-path][Load Path]]
    - [[#window-splits][Window Splits]]
  - [[#package-setup][Package Setup]]
    - [[#package][Package]]
    - [[#customize][Customize]]
  - [[#aesthetics][Aesthetics]]
    - [[#about-1][About]]
    - [[#remove-pointless-gui][Remove Pointless GUI]]
    - [[#line-numbers-stuff][Line Numbers Stuff]]
    - [[#general-fonts][General Fonts]]
    - [[#themes][Themes]]
  - [[#completion][Completion]]
    - [[#ivy-completion][Ivy Completion]]
    - [[#company][Company]]
  - [[#evil][Evil]]
    - [[#about-2][About]]
    - [[#the-evil-mode][The Evil Mode]]
    - [[#general-keybindings][General Keybindings]]
    - [[#the-evil-collection][The Evil Collection]]
    - [[#the-evil-commentary][The Evil Commentary]]
    - [[#the-evil-surround][The Evil Surround]]
    - [[#undo-fu][Undo-Fu]]
  - [[#avy][Avy]]
    - [[#setup][Setup]]
  - [[#org][Org]]
    - [[#about-3][About]]
    - [[#main-org][Main Org]]
    - [[#org-blog][Org Blog]]
    - [[#font-setup][Font Setup]]
    - [[#prettify-symbols-in-org-mode][Prettify Symbols in Org Mode]]
    - [[#org-setup][Org Setup]]
    - [[#visual-column-mode][Visual Column Mode]]
    - [[#org-bullets][Org Bullets]]
    - [[#evil-org][Evil Org]]
    - [[#org-prettier-tables][Org Prettier Tables]]
    - [[#org-tempo][Org Tempo]]
    - [[#org-tables-of-content][Org Tables Of Content]]
    - [[#super-agenda][Super Agenda]]
  - [[#helpful][Helpful]]
  - [[#magit][Magit]]
    - [[#about-4][About]]
  - [[#snippets][Snippets]]
  - [[#dired][Dired]]
    - [[#subtree][Subtree]]
  - [[#language-modes][Language Modes]]
    - [[#about-5][About]]
    - [[#autohotkey][AutoHotkey]]
    - [[#latex][LaTeX]]
    - [[#powershell][Powershell]]
    - [[#python][Python]]
    - [[#ruby][Ruby]]
    - [[#spell-checking][Spell Checking]]
    - [[#vbscript][VBScript]]
    - [[#web][Web]]
    - [[#yaml][YAML]]
  - [[#fun][Fun]]
    - [[#discord][Discord]]
#+END_QUOTE

** The Basics
*** About

Including a few nice bindings that I can't live without, and my name and stuff: 

*** Improve Start-Up Time

This! What is /this/?

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
;;;; -*- lexical-binding: t; -*- 
#+end_src

Delay garbage collection.

=most-positive-fixnum= is an elegant way of avoiding just having a large number there, like I've seen a lot when looking at this. 

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (setq gc-cons-percentage 0.6)
  (setq gc-cons-threshold most-positive-fixnum)
#+end_src

*** Maximise Window

Upon starting Emacs (on Windows 10, at least), it's annoying that it's not full screen:

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
(add-hook 'emacs-startup-hook 'toggle-frame-maximized)
#+end_src

*** Scratch Buffer and Startup Info

Change the scratch buffer and disable the startup messages.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (setq inhibit-startup-message t)
  (setq initial-scratch-message (concat ";;  Emacs loaded in " (emacs-init-time) ", according to (emacs-init-time), at least...\ 


  "))
#+end_src

I used /Dashboard/ for a short while, but I've decided to make this config as simple as I can.

*** My Details

Added because it's sometimes nice to have these around (although I've not really needed them here in my Emacs journey, thus far...).

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (setq user-full-name "Julian Orchard")
  (setq user-mail-address "hello@julianorchard.co.uk")
#+end_src

*** Escape Actually Escapes

This is an incredibly useful binding, and one the lack of which /seriously/ threw me when first using emacs.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)
#+end_src

**** TODO Use General.el to set this keybind?
<2022-08-12 Fri>

*** Mouse

Set scrolling amount.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (setq mouse-wheel-scroll-amount '(1 ((shift) . 1))) 
  (setq mouse-wheel-progressive-speed nil)
  (setq mouse-wheel-follow-mouse 't)
  (setq scroll-step 1)
#+end_src

*** Parenthesis Mode

Spending any longer than 5 seconds in a buffer of lisp will require this, and it's nice to have generally: 

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (show-paren-mode t)
#+end_src

*** Minimizing Lockfiles and Tempfiles

One of the wost things I found about initially using Emacs was how quickly simply opening files cluttered up everything. Get rid of the temporary files, as much as possible. Backup files to =~/Documents/Emacs-backup-dir/= too, out of the way as much as is reasonable...

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (setq backup-directory-alist `(("." . "~/.cache/emacs/")))
  (setq backup-by-copying t
        delete-old-versions t
        kept-new-versions 5
        kept-old-versions 5
        version-control t)
  (setq create-lockfiles nil)
#+end_src

*** UTF-8

Yes, thank you.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (prefer-coding-system 'utf-8)
  (set-default-coding-systems 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
  (setq default-buffer-file-coding-system 'utf-8)
#+end_src

*** Dialogue Boxes

No, thank you.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (setq use-dialog-box nil)
#+end_src

*** Yes/No, or Y/N

Y/N, thank you.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (defalias 'yes-or-no-p 'y-or-n-p)
#+end_src

*** Load Path

Paths to load, for Elisp by me or others.

|-------------------------+------------------------------------------------------------|
| Path                    | Purpose                                                    |
|-------------------------+------------------------------------------------------------|
| =~/.emacs.d/lisp/=      | Custom stuff, eventually, everything will be split up here |
| =~/.emacs.d/site-lisp/= | Non-MELPA / ELPA Packages, cloned from Github or E-wiki    |
|-------------------------+------------------------------------------------------------|

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (add-to-list 'load-path
               (concat (getenv "HOMEPATH") "/.emacs.d/lisp/"))
#+end_src

*** Window Splits

Default the window splits to be horizontal all the time. This is almost always what I want, so it does make sense for me to do it like this

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (setq split-width-threshold 1 )
#+end_src

** Package Setup
*** Package

So this is basically setting the package-archives Melpa and Elpa.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (require 'package)
  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")
                           ("elpa" . "https://elpa.gnu.org/packages/")))
  (package-initialize)
#+end_src

This refreshes the package contents, I believe.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (unless package-archive-contents
   (package-refresh-contents))
  (unless (package-installed-p 'use-package)
     (package-install 'use-package))
#+end_src

And now we =require 'use-package=.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src

*** Customize

I'm not sure if this really /belongs/ here, but we can move some of the variables set by the =customize= interface to a different file (according to [[https://stackoverflow.com/questions/5052088/what-is-custom-set-variables-and-faces-in-my-emacs][this]], anyway).

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (setq custom-file "~/.emacs.d/custom.el")
  (load custom-file)
#+end_src

** Aesthetics
*** About

This part used to be a lot more involved, but I've decided I want to keep things more minimal to actually enjoy /using/ this software more, rather than endlessly making tiny aesthetic changes. I'm therefore planning on using the stock Emacs themes (or very similar), and maybe a light and dark version.

*** Remove Pointless GUI

But first, get rid of the more useless stuff, and mess with the line-numbers (needs work):

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
  (tooltip-mode -1)
  (set-fringe-mode 5)
  (menu-bar-mode -1)
  (setq visible-bell t)
  ;; Don't 
#+end_src

*** Line Numbers Stuff

This needs reviewing...

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (column-number-mode)
  (global-display-line-numbers-mode)
  (setq display-line-numbers-type 'relative)
  ;; (dolist (rm-ln-hook '(org-mode-hook
  ;;                       term-mode-hook
  ;;                       shell-mode-hook
  ;;                       treemacs-mode-hook
  ;;                       eshell-mode-hook))
  ;;   (add-hook rm-ln-hook (lambda () (global-display-line-numbers-mode))))
#+end_src

**** TODO Get Line Numbering Working
*** General Fonts

I used to use ET Book for some really nice looking Org-documents, especially. However, I've stopped this and now just use Fira (I also use a [[version https://github.com/zwaldowski/Fira/tree/zwaldowski/mod-new/otf][fork]] for the /italicised/ version).

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (set-face-attribute 'italic nil :font "Fira Mono" :height 105)
  (set-face-attribute 'default nil :font "Fira Code Retina" :height 110)
#+end_src

I'm not massively attached to this font; I do like it a lot but I don't mind changing it if I decide the fact it doesn't have an italic version officially is a problem. 

*** Themes

I used to use Doom themes. I am now +planning on+ using the default dark and light themes built into Emacs.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (defun set-dark-theme ()
    (interactive)
    "Sets the dark version of the default theme"
    (set-background-color "black")
    (set-foreground-color "white"))

  (defun set-light-theme ()
    (interactive)
    "Sets the light version of the default theme"
    (set-background-color "white")
    (set-foreground-color "black"))
#+end_src

For switching themes, I wanted to do it automatically if I'm working in the evening... I initially tried something like /this/:

#+begin_src elisp
  (if (time-less-p (parse-time-string "2022-08-19 23:00:00")
               (current-time))
      ...)
#+end_src

The problem was that I was trying to use a full date/time for the comparison, whereas the solution (which sadly, in the end I had to [[https://stackoverflow.com/questions/14760567/emacs-auto-load-color-theme-by-time][look up]]) turned out to be just using /hours/ of the day:

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (if (member (string-to-number (substring (current-time-string) 11 13))
              (number-sequence 7 20))
      (set-light-theme)
    (set-dark-theme))
#+end_src

I find elisp tricky.

...

+=Ctrl+F1= (for /Tomorrow Night/) and =Ctrl+F2= (for /Solarized/) are used to switch between them (found [[https://emacs.stackexchange.com/questions/45799/keyboard-shortcuts-for-applying-a-theme][here]]).+

This /was/ what I used, when using Doom Emacs Themes;

#+begin_src elisp
  (use-package doom-themes
    :init (load-theme 'doom-tomorrow-night t)
    :config
    (global-set-key (kbd "C-<f1>")
                    (lambda () (interactive)
                      (load-theme 'doom-tomorrow-night t)
                      (here/org-font-setup)))
    (global-set-key (kbd "C-<f2>")
                    (lambda () (interactive)
                      (load-theme 'doom-solarized-light t)
                      (here/org-font-setup))))
  (use-package doom-modeline
    :ensure t
    :init (doom-modeline-mode 1)
    :custom ((doom-modeline-height 20)))
  (use-package solaire-mode
    :init (solaire-global-mode +1))
#+end_src

But I do still want /all-the-icons/:

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package all-the-icons
    :ensure t)
#+end_src

** Completion
*** Ivy Completion

Completion in the minibuffer.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
    (use-package ivy
      :diminish
      :bind (("C-s" . swiper)
             :map ivy-minibuffer-map
             ("TAB" . ivy-alt-done)	
             ("C-j" . ivy-next-line)
             ("C-k" . ivy-previous-line)
             :map ivy-switch-buffer-map
             ("C-k" . ivy-previous-line)
             ("C-l" . ivy-done)
             ("C-d" . ivy-switch-buffer-kill)
             :map ivy-reverse-i-search-map
             ("C-k" . ivy-previous-line)
             ("C-d" . ivy-reverse-i-search-kill))
      :config
      (ivy-mode 1))
    (global-set-key (kbd "C-x C-b") 'ivy-switch-buffer)
    (global-set-key (kbd "C-x C-k") 'kill-this-buffer)
#+end_src

**** TODO Ivy completion bindings with General
*** Company

For completion /outside/ the minibuffer.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package company
    :custom
    (company-global-modes '(not shell-mode eaf-mode))
    :config
    (global-company-mode 1))
  ;; (setq company-backends (mapcar #'company-mode/backend-with-yas company-backends)))
#+end_src

** Evil
*** About

The most vital Emacs package for me.

*** The Evil Mode

=use-package= to get Evil mode installed and configured. 

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package evil
    :ensure t
    :demand 
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-i-jump nil)
    (setq evil-undo-system 'undo-fu)
    :config
    (evil-mode 1)
    (setq evil-split-window-below t)
    (setq evil-vsplit-window-right t)
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)
    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal))
#+end_src

*** General Keybindings

I'm going to use =general.el= to manage some of these bindings. 

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package general
    :ensure t
    :config
    (general-evil-setup t)
    (general-define-key
     :states '(normal visual)
     :prefix "SPC"
     "SPC" 'execute-extended-command
     "r" 'eval-region
     )
    (general-define-key
     :states 'normal
     :prefix "SPC"
     "q" 'evil-quit
     "h" 'evil-window-left
     "j" 'evil-window-down
     "k" 'evil-window-up
     "l" 'evil-window-right
     "b" 'ivy-switch-buffer
     "f" 'find-file-other-window
     "tf" 'org-babel-tangle
     "ts" 'org-time-stamp
     "a" 'org-agenda
     "c" 'org-capture
     "1" 'delete-other-windows
     "0" 'delete-window
     "2" 'split-window-below
     "3" 'split-window-right
     "{" 'shrink-window-horizontally
     "}" 'enlarge-window-horizontally
     "+" 'balance-windows
     "[" 'set-light-theme
     "]" 'set-dark-theme
     ))
#+end_src

**** TODO Spread some General bindings around the config file

*** The Evil Collection

Adds evil-bindings to a wide range of Emacs applications without having to do anything!

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))
#+end_src

*** The Evil Commentary

Tim Pope's incredible [[https://github.com/tpope/vim-commentary][commentary.vim]], ported to Evil-mode.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package evil-commentary
    :after evil
    :diminish
    :config (evil-commentary-mode +1))
#+end_src

*** The Evil Surround

And another Tpope plugin ported to Emacs (which I don't actually use in Vim too much, but want to start using more often), [[https://github.com/tpope/vim-surround][vim-surround]].

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
(use-package evil-surround
  :ensure t
  :config
  (global-evil-surround-mode 1))
#+end_src

*** Undo-Fu

Undo and redo; used by Evil-mode to enable =Ctrl+r= functionality.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package undo-fu)
#+end_src 

** Avy
*** Setup

This plugin is for jumping to text in the current view. I used a similar plugin in Atom, but never tried vim-easymotion. 

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
(use-package avy
  :ensure t
  :config
  (general-define-key
     :states 'normal
     :prefix "SPC"
     "," 'avy-goto-char))
#+end_src

Not sure if I'll end up using this much right now, but want to try it out. 

** Org
*** About

One of the biggest draws to Emacs, for me, has become Org-mode. 

*** Main Org

This is the main org-mode block.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package org
    :pin org
    :commands (org-capture org-agenda)
    :hook (org-mode . here/org-mode-setup)
    (org-mode . here/org-mode-symbols-setup)
    ;; (org-mode . here/org-capture-workflow)
    :config
    (setq org-ellipsis " ⌄")
    (set-face-underline 'org-ellipsis nil)
    (setq header-line-format " ")
    (setq org-agenda-files
          '("~/org/" "~/config/"))
    (setq org-duration-format (quote h:mm))
    (setq org-hide-emphasis-markers t)
    (setq org-todo-keywords
          '((sequence "TODO(t)" "PEND(p)" "|" "DONE(d)" "CANC(c)")
            (sequence "|" "FIVE(5)" "FOUR(4)" "THRE(3)" "TWO(2)" "ONE(1)")))
    (setq org-priority-faces
          '((?A . (:foreground "red"))
            (?B . (:foreground "orange"))
            (?C . (:foreground "yellow"))))
    (setq org-capture-templates
          '(("w" "Wessex" entry (file+headline "~/org/wessex.org" "Tasklist")
             "* TODO %?" :prepend t)
            ("p" "Personal" entry (file+headline "~/org/personal.org" "Tasklist")
             "* TODO %?" :prepend t)
            ("j" "Journal" entry (file+datetree "~/org/journal.org")
             "* Entry for %U\n%?")
            )))
#+end_src

Note, I do the org-capture-templates part with [[https://emacs.stackexchange.com/questions/30169/set-org-capture-datetree-write-on-top-of-the-file][this]], because I want to put items at the top of the list.


*** Org Blog

I've started using Org-blog for my personal site:

#+begin_src elisp
  (use-package org-static-blog
    :ensure t
    :config
    (setq org-static-blog-publish-title "Hylobatid")
    (setq org-static-blog-publish-url "https://hylobatid.github.io/")
    (setq org-static-blog-publish-directory "~/hylobatid.github.io/")
    (setq org-static-blog-posts-directory "~/hylobatid.github.io/blog/posts/")
    (setq org-static-blog-drafts-directory "~/hylobatid.github.io/blog/drafts/")
    (setq org-static-blog-enable-tags t)
    (setq org-static-blog-use-preview t)
    (setq org-export-with-toc nil)
    (setq org-export-with-section-numbers nil)
    (setq org-static-blog-page-header
          "<meta name=\"author\" content=\"Hylobatid\">
  <meta name=\"referrer\" content=\"no-referrer\">
  <link href= \"static/style.css\" rel=\"stylesheet\" type=\"text/css\" />
  <link rel=\"icon\" href=\"static/favicon.ico\">")
    (setq org-static-blog-page-preamble
          "<div class=\"header\">
    <a href=\"https://hylobatid.github.io\">Hylobatid</a>
  </div>")
    (setq org-static-blog-page-postamble
          "<div id=\"archive\">
    <a href=\"https://hylobatid.github.io/archive.html\">Other posts</a>
  </div>
  <footer>
    Made with <a href=\"https://github.com/bastibe/org-static-blog\">Org</a>.
  </footer>")
    (setq org-static-blog-index-front-matter
          "<h1>Thoughts</h1>\n"))
#+end_src

Lots of it is a work in progress.

*** Font Setup

I started using this setup, below (edited from Davwils /Emacs From Scratch/), but I've subsequently decided upon a more plain configuration (without the Serif fonts I used here):

#+begin_src elisp
  (defun here/org-font-setup ()
    ;; Replace list hyphen with dot
    (font-lock-add-keywords 'org-mode
                            '(("^ *\\([-]\\) "
                               (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))
    ;; Set faces for heading levels
    ;; (dolist (face '((org-document-title . 2.0)
    ;;                 (org-level-1 . 1.4)
    ;;                 (org-level-2 . 1.2)
    ;;                 (org-level-3 . 1.1)
    ;;                 (org-level-4 . 1.1)
    ;;                 (org-level-5 . 1.0)
    ;;                 (org-level-6 . 1.0)
    ;;                 (org-level-7 . 1.0)
    ;;                 (org-level-8 . 1.0)))
    ;;   (set-face-attribute (car face) nil :font "ETBookOT" :weight 'Light :height (cdr face)))

    (dolist (face '((org-document-title . 2.0)
                    (org-level-1 . 1.0)
                    (org-level-2 . 1.0)
                    (org-level-3 . 1.0)
                    (org-level-4 . 1.0)
                    (org-level-5 . 1.0)
                    (org-level-6 . 1.0)
                    (org-level-7 . 1.0)
                    (org-level-8 . 1.0)))
      (set-face-attribute (car face) nil :inherit 'fixed-pitch))

    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-block nil :foreground nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-table nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-formula nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-code nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-table nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-verbatim nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch)
    (set-face-attribute 'line-number nil :inherit 'fixed-pitch)
    (set-face-attribute 'line-number-current-line nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-quote nil :inherit 'fixed-pitch :slant 'italic))
#+end_src

*** Prettify Symbols in Org Mode

I found this method on a Reddit post:

#+begin_src elisp
  (add-hook 'org-mode-hook (lambda ()
                             "Prettify Symbols Setup for Org Documents"
                             (push '("[ ]" . "☐") prettify-symbols-alist)
                             ;;etc.
                             ))
#+end_src

But ended up doing so many it's in its own funcion =here/org-mode-symbols-setup=.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (defun here/org-mode-symbols-setup ()
    "Prettify Symbols Setup for Org Documents"
    (push '("[ ]" . "☐") prettify-symbols-alist)
    (push '("[X]" . "☑" ) prettify-symbols-alist)
    (push '("[-]" . "○" ) prettify-symbols-alist)
    (push '("#+BEGIN_SRC" . "→" ) prettify-symbols-alist)
    (push '("#+END_SRC" . "←" ) prettify-symbols-alist)
    (push '("#+begin_src" . "→" ) prettify-symbols-alist)
    (push '("#+end_src" . "←" ) prettify-symbols-alist)
    (push '("#+BEGIN_EXAMPLE" . "e.g. →" ) prettify-symbols-alist)
    (push '("#+END_EXAMPLE" . "←" ) prettify-symbols-alist)
    (push '("#+begin_example" . "e.g. →" ) prettify-symbols-alist)
    (push '("#+end_example" . "←" ) prettify-symbols-alist)
    (push '("#+BEGIN_QUOTE" . "“" ) prettify-symbols-alist)
    (push '("#+END_QUOTE" . "”" ) prettify-symbols-alist)
    (push '("#+begin_quote" . "“" ) prettify-symbols-alist)
    (push '("#+end_quote" . "”" ) prettify-symbols-alist)
    (push '("#+title:" . "⒯") prettify-symbols-alist)
    (push '("#+TITLE:" . "⒯") prettify-symbols-alist)
    (push '("#+options:" . "⌥") prettify-symbols-alist)
    (push '("#+OPTIONS:" . "⌥") prettify-symbols-alist)
    (push '("#+author:" . "⒜") prettify-symbols-alist)
    (push '("#+AUTHOR:" . "⒜") prettify-symbols-alist)
    (push '("#+date:" . "⒟") prettify-symbols-alist)
    (push '("#+DATE:" . "⒟") prettify-symbols-alist)
    (push '("#+description:" . "…") prettify-symbols-alist)
    (push '("#+DESCRIPTION:" . "…") prettify-symbols-alist)
    (push '("#+results:" . " result ⇒ ") prettify-symbols-alist)
    (push '("#+RESULTS:" . " result ⇒ ") prettify-symbols-alist)
    (push '("#+property:" . "∷") prettify-symbols-alist)
    (push '("#+PROPERTY:" . "∷") prettify-symbols-alist)
    (push '("[#A]" . "⬆") prettify-symbols-alist)
    (push '("[#B]" . "■") prettify-symbols-alist)
    (push '("[#C]" . "⬇") prettify-symbols-alist)
    ;; (push '("TODO" . "☐") prettify-symbols-alist)
    ;; (push '("PEND" . "○") prettify-symbols-alist)
    ;; (push '("DONE" . "☑") prettify-symbols-alist)
    ;; (push '("CANC" . "☒") prettify-symbols-alist)
    (prettify-symbols-mode))
#+end_src

*** Org Setup

Including the removal of =variable-line-mode t=.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
 (defun here/org-mode-setup ()
    (org-indent-mode)
    (visual-line-mode 1))
 #+end_src

*** Visual Column Mode

Centring org-mode docs. 

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (defun here/org-mode-visual-fill ()
    (setq visual-fill-column-width 100
          visual-fill-column-center-text t)
    (visual-fill-column-mode 1))
 (use-package visual-fill-column
    :hook (org-mode . here/org-mode-visual-fill))
 #+end_src

*** Org Bullets

Better bullet points and indentation.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package org-bullets
    :hook (org-mode . org-bullets-mode)
    :custom
    ;; (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))
    ;; (org-bullets-bullet-list '("\u200b" " " "◉" "-")))
   (org-bullets-bullet-list '("●" "○")))

 #+end_src
 
*** Evil Org

Evil stuff for org specifically.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package evil-org
    :ensure t
    :after org
    :hook (org-mode . (lambda () evil-org-mode))
    :config
    (require 'evil-org-agenda)
    (evil-org-agenda-set-keys))
 #+end_src

*** Org Prettier Tables

Prettier Org tables, please (they're lovely by default, but this makes them even nicer.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  ;; (progn
  ;;   (add-to-list 'load-path "~/.emacs.d/site-lisp")
  ;;   (require 'org-pretty-table)
  ;;   (add-hook 'org-mode-hook (lambda () (org-pretty-table-mode))))
 #+end_src

*** Org Tempo

This allows you to use =<s= to quickly insert a block of script, or =<q= to quickly insert a quote.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (require 'org-tempo)
#+end_src

*** Org Tables Of Content

This is a really nice plugin (that I mainly use for /this very project/) that generates a nice table of contents on the saving of the document. The following is /basically/ taken from the [[https://github.com/snosov1/toc-org][repo]], but it works so I'm happy (and I don't want/need to use it with Markdown).

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package toc-org
    :config
    (add-hook 'org-mode-hook 'toc-org-mode))
#+end_src

*** Super Agenda

Not using this /yet/. 

#+begin_src elisp
  (use-package org-super-agenda
    :config
    (let ((org-super-agenda-groups
           '((:name "Today"
                    :time-grid t
                    :todo "TODAY")
             (:name "This Week"
                    :time-grid t
                    :todo "THIS WEEK")
             (:name "Important"
                    ;; Don't need this yet, but:
                    ;; :and (:tag "bills" :tag "another_important_tag")
                    :priority "A")
             (:todo "PENDING" :order 8))))
      (org-agenda nil "a")))
#+end_src

** Helpful

This is a todo, really. Taken from Daviwils dotfiles.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package helpful
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))
  #+end_src

** Magit
*** About

+I need to get this working with my SSH key.+ I'm not using this at the moment, so leaving it commented for a moment. I /will/ make use of it in the future, but it's not a priority.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  ;; (use-package magit
  ;;   :ensure t
  ;;   :defer 5
  ;;   :commands magit-status
  ;;   :custom
  ;;   (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))
#+end_src

**** TODO [#C] Get Magit working
<2022-09-02 Fri>

** Snippets

It's now working, /a bit/; mainly thanks to [[http://www.howardism.org/Technical/Emacs/templates-tutorial.html][this nice post]]!

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package yasnippet
    :ensure t
    :init
    (yas-global-mode 1)
    :config
    (add-to-list 'yas-snippet-dirs (locate-user-emacs-file "snippets")))
#+end_src

** Dired
*** Subtree 

[[https://xenodium.com/drill-down-emacs-dired-with-dired-subtree/][Drill down Emacs dired with dired-subtree]], a fairly useful addition to Dired. 

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package dired-subtree :ensure t
    :after dired
    :config
    (bind-key "<tab>" #'dired-subtree-toggle dired-mode-map)
    (bind-key "<backtab>" #'dired-subtree-cycle dired-mode-map))
#+end_src

** Language Modes
*** About

Some language-specific stuff, which modes to pick, etc.

*** AutoHotkey

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package ahk-mode
    :config
    (add-to-list 'auto-mode-alist
                 '("\\.ahk" . ahk-mode)))
#+end_src

*** LaTeX

Or should I say XeLaTeX!? (Use XeLaTeX by default export.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (setq latex-run-command "xelatex")
#+end_src

This extremely helpful [[https://emacs.stackexchange.com/questions/169/how-do-i-reload-a-file-in-a-buffer][Stack Overflow User]] makes my workflow nicer with LaTeX.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (defun here/revert-buffer-no-confirm ()
    "Revert buffer without confirmation."
    (interactive)
    (revert-buffer :ignore-auto :noconfirm))

  (global-set-key (kbd "C-c C-1") 'here/revert-buffer-no-confirm)
#+end_src

And this allows the PDF document to refresh without confirmation... again, from [[https://stackoverflow.com/questions/42330517/force-docview-mode-to-show-updated-file-without-confirmation][Stack Overflow]]!

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (setq revert-without-query '(".pdf"))
#+end_src

*** Powershell

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package powershell
    :config
    (add-to-list 'auto-mode-alist
                 '("\\.ps1" . powershell)))
#+end_src

*** Python

Something like this (but more, quite a bit more);

#+begin_src elisp
(python-mode)
#+end_src

**** TODO Python Mode
*** Ruby

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
    (add-to-list 'auto-mode-alist
                 '("\\.\\(?:cap\\|gemspec\\|irbrc\\|gemrc\\|rake\\|rb\\|ru\\|thor\\)\\'" . ruby-mode))
    (add-to-list 'auto-mode-alist
                 '("\\(?:Brewfile\\|Capfile\\|Gemfile\\(?:\\.[a-zA-Z0-9._-]+\\)?\\|[rR]akefile\\)\\'" . ruby-mode))
#+end_src

*** Spell Checking

#+begin_src elisp
  (require 'ispell)
  (setq ispell-program-name "c:/Users/jorchard/aspell/aspell.exe")
  (setq ispell-local-dictionary "en_GB")
  (setq mail-user-agent 'message-user-agent)
  (require 'message-outlook)
#+end_src

*** VBScript

TODO, or not to bother... potentially not worth looking at.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (setq auto-mode-alist
        (append '(("\\.\\(vbs\\|wsf\\)$" . vbscript-mode))
                auto-mode-alist))
#+end_src

*** Web

A general mode for web-development stuff.

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package web-mode
    :mode
    (("\\.tpl\\.php\\'" . web-mode)
     ("\\.erb\\'" . web-mode)))
#+end_src

*** YAML

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
  (use-package yaml-mode)
#+end_src

** Fun
*** Discord

Tell /everyone/ on Discord you use Emacs (otherwise what's the point in using it at all)?!

#+begin_src elisp :tangle ~/.emacs.d/init.el :mkdirp yes
    (if (and (eq system-type 'windows-nt)
             (equal user-login-name "julia"))
        (use-package elcord
          :config
          (elcord-mode 1)))
#+end_src

Initially, I wanted to do this by testing to see if =discord= is an executable on the system, but I can't get that working with Windows easily (and on my work machine I can't do certain things) so in the end I just check if the username is /julia/, which is my home PC username (it was automatically shortened from my email when I logged into the PC with a Microsoft account).

