#!/bin/sh

# userresources=$HOME/.config/X11/Xresources
# usermodmap=$HOME/.config/X11/Xmodmap
# sysresources=/etc/X11/xinit/Xresources
# sysmodmap=/etc/X11/xinit/.Xmodmap

# Systemctl Fix
#systemctl --user set-environment DISPLAY=:0

setxkbmap -layout gb

xrdb -merge "$HOME"/.config/X11/Xresources

# if [ -d /etc/X11/xinit/xinitrc.d ]
# then
#   for f in /etc/X11/xinit/xinitrc.d/?*.sh
#   do
#     # If $f executable, execute
#     [ -x "$f" ] && . "$f"
#   done
#   unset f
# fi

# [ -x /usr/bin/udiskie ] && exec udiskie

# exec awesome
# exec bspwm
exec i3
