#!/bin/bash

# Title:	brightness
# By: 		OfficialKingJulian
# Tag Added:	02-02-2020
# Description:  Control the backlight brightness CLI

file=/sys/class/backlight/intel_backlight/brightness

if [ ! -z ${1} ] && [ ${1} -lt 100 ] && [ ${1} -gt 0 ] ; then
  echo $(((3000/100)*${1})) > ${file}
else
  echo "This command requires a value between 1 and 100."
fi

