#!/bin/bash

# Title:	dotfiles/.bin/dunst-test
# By: 		OfficialKingJulian
# Tag Added:	24-02-2020
# Description:  Quickly create a load of dunst notifications

count=1
slen=${1}
if [[ -z ${slen} ]] ; then slen=1 ; fi
while true ; do 
  notify-send \
  "Dunst Test ${count}" \
  "This subheading is test number ${count}" 
  count=$((count+1)) 
  sleep ${slen}
done
