#!/bin/sh

##   font-install-arch  ---  Quickly install fonts from online, on my ThinkPad.

# Copyright (c) 2023 Julian Orchard <jorchard@pm.me>

## Description:

# Shell script to quickly install fonts, from online, on my ThinkPad x220.

# But obviously *may* work on many nix systems.

## License:

# See /LICENSE file in the root of this repository.

## Code:

FONT_INSTALL_PATH="/usr/local/share/fonts/"
FONT_LOCAL_PATH="${HOME}/Fonts/"

unzip_and_find_file () {
  mkdir -p "${FONT_LOCAL_PATH}"
  zip_file="${1}"
  unzip_folder="${1/%.zip/}"

  # Make directory to unzip to:
  # /home/[user]/Fonts/[zip_file_name]/
  unzip_path="${FONT_LOCAL_PATH}/${unzip_folder}/"
  mkdir -p "${unzip_path}"
  unzip ${zip_file} -d ${unzip_path}

  # Loop all font files and install 'em:
  for $i in "${unzip_path}/*.ttf" "${unzip_path}/*.otf"; do
    handle_file "${i}"
  done

  echo "$1.ttf"
}

font_ext_get () {
  # Return the font ext
  echo "${1##*.}"
}

handle_file () {
  case $1 in
    # Okay, so basically we only need one case
    # for *either* ttf or otf. We can just get the
    # file extension, remove the '.', and run it:
    *.ttf|*.otf)
      font_ext=$(font_ext_get "$1")
      echo "We have a ${font_ext}! ${1}"
      # sudo mkdir -p "${FONT_PATH}/ttf/"
      ;;
    # Handle zip files as input
    *.zip)
      echo "Unzipping input folder..."
      handle_file $(unzip_and_find_file "$1")
      ;;
    # We do want input, basically:
    *) echo "${1} is not valid, please input the file name." # && exit 0
  esac
}

handle_file "${1}"
