#!/usr/bin/env ruby

##   hack  ---  Makes it look like you're doing some hacking...

# Copyright (c) 2022   Julian Orchard <jorchard@pm.me>

## Description:

# Make it look like you're hacking! Doesn't work, for me, on Windows.

## License:

# See /LICENSE file in the root of this repository.

## Code:

# * TODO: add if remote
#   SCHEDULED: <2022-12-19>
#   this doesn't currently work with Cygwin, and I can't use
#   gems on my local (work) machine
#   Julian <jorchard@pm.me>

require 'colorize'

def finish_hack
  puts "\nHack progress at 100%.".red.underline
  if ARGV.empty?
    puts "\n\n   --->>   HACK COMPLETE.\n".green.bold
  else
    puts "\n\n   --->>   HACK OF ".green.bold + ARGV.join(" ").upcase.light_green.italic + " COMPLETE.\n".green.bold
  end
  exit
end

def main
  na = ["5","11","19","30","36","41","52","69","74","88","96","99","100"]
  colors = ["green","cyan","light_blue","light_cyan","light_green"]
  c = 0
  loop do
    begin
      sleep(1.0/5.0)
      case rand(0..7)
      when 0..5
        lc = rand(5..12)
        i = 0
        puts "\n"
        loop do
          i = i + 1
          quickvar = ('!'..'~').to_a.shuffle[0,rand(7..200)].join
          puts quickvar.to_s.send(colors.sample)
          break if i == lc
        end
      when 6
        puts "\nGenerating hack string...\n"
      when 7
        finish_hack if na[c] == "100"
        puts "\nThe Hack Is Currently Ongoing.".bold
        puts "Please do not touch the keyboard until the time is right.".bold
        puts "\nHack progress at ".bold + na[c].red.bold + "%.\n\n".bold
        c = c + 1
      end
    rescue Interrupt
      finish_hack
    end
  end
end

main

# vi: ft=ruby
