#!/usr/bin/env sh

set -euf

##   layout  ---  Set default screen layouts.

# Copyright (c) 2023 Julian Orchard <jorchard@pm.me>

## Description:

# Set default screen layouts using xrandr and resetting the
# wallpaper, basically.

## License:

# See /LICENSE file in the root of this repository.

## Code:

LAPTOP_DISPLAY="eDP-1"
MONITOR_DISPLAY="HDMI-1-0"

laptop() {
  xrandr --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1-0 --off
  # xrandr --output LVDS1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output DP3 --off --output HDMI1 --off --output HDMI2 --off --output HDMI3 --off --output VGA1 --off --output VIRTUAL1 --off
}

desktop() {
  xrandr --output LVDS1 --primary --mode 1366x768 --pos 157x1050 --rotate normal --output DP1 --off --output DP2 --off --output DP3 --off --output HDMI1 --off --output HDMI2 --off --output HDMI3 --off --output VGA1 --mode 1680x1050 --pos 0x0 --rotate normal --output VIRTUAL1 --off
}

desktop_only() {
  xrandr --output LVDS1 --off --output DP1 --off --output DP2 --off --output DP3 --off --output HDMI1 --off --output HDMI2 --off --output HDMI3 --off --output VGA1 --mode 1680x1050 --pos 0x0 --rotate normal --output VIRTUAL1 --off
}

work() {
  xrandr --output eDP-1 --mode 1920x1080 --pos 3840x1080 --rotate normal --output HDMI-1-0 --mode 3840x2160 --pos 0x0 --rotate normal --dpi 150 # --scale 1.25x1.25
}

home_left() {
  # Laptop on the left:
  xrandr --output $LAPTOP_DISPLAY --primary --auto --output $MONITOR_DISPLAY --auto --right-of $LAPTOP_DISPLAY
}

home_right() {
  # Laptop on the right:
  xrandr --output $LAPTOP_DISPLAY --primary --auto --output $MONITOR_DISPLAY --auto --left-of $LAPTOP_DISPLAY
}

set_background() {
    # Day of the week; Monday == Oneday
    day_of_the_week=$(date +%u)
    # Set these as arguments, to be used in the `feh` command!
    set -- --randomize --image-bg "#1E1E2E"
    if [ "${day_of_the_week}" -gt 5 ] ; then
        # Fun Primeagen Wallpapers
        feh "${@}" "${HOME}/Pictures/cringe-wallpapers/" --bg-max

    else
        # Non-embaressing Wallpapers
        feh "${@}" "${HOME}/Pictures/normie-wallpapers/" --bg-fill
    fi
}

usage() {
  echo "Accepted arguments for this command are 'laptop', 'desktop', and 'deskonly'."
}

[ -z "${1}" ] && usage && exit 0

case $1 in
  laptop)
    laptop
    set_background
    ;;
  desktop)
    desktop
    set_background
    ;;
  deskonly)
    desktop_only
    set_background
    ;;
  work)
    work
    set_background
    ;;
  home_left)
    home_left
    set_background
    ;;
  home_right)
    home_right
    set_background
    ;;
  *)
    usage
esac

