#!/bin/bash

# Title:	      pmbridge-status
# By: 		      Julian Orchard <jorchard@pm.me>
# Tag Added:	  18-06-2020
# Description:  Show whether the daemonized protonmail bridge 
#               service is running, with an icon, for polybar.
#
#               Again, this is super old now...

stat=$(screen -list | grep protonmailbridge)
if [[ ! ${stat} = "" ]] ; then 
  printf "" 
else 
  printf ""
fi
