#!/bin/bash

# File:        screenshot
# Author:      Julian Orchard <hello@julianorchard.co.uk
# Tag Added:   2023-01-31
# Description: Simple screenshot capture from ages ago... 

# Define Name
name=${1}
if [[ name = "" ]] ; then name="test" ; fi

# Capture
scrot ${HOME}/%Y-%m-%d-${name}.jpg -e $(notify-send "Screenshot Captured" "%Y-%m-%d-$name")  

