#!/bin/bash

# File:        vpn-protonvpn-status
# Author:      Julian Orchard <hello@julianorchard.co.uk
# Tag Added:   2023-01-31
# Description: Proton VPN Status for bar.

country=$(protonvpn s | grep "Country" | sed -e 's/Country://g;s/ //g')
stat=$(protonvpn s | grep "Status" | sed -e "s/Status://g;s/ //g")
#printf "  $(protonvpn s | grep "Status" | sed -e "s/Status://g;s/ //g;s/Disconnected/down/;s/Connected/${country}/")"

if [[ ${stat} = Connected ]] ; then
  printf " ${country}"
else 
  printf ""
fi
